version: '3'
services:

  lazarillo_flask_backend:
    build:
      context: app
      dockerfile: Dockerfile
    image: lazarillo_flask_backend
    container_name: lazarillo_flask_backend
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 80
      MONGODB_DATABASE: lazarillo
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongo_password
      MONGODB_HOSTNAME: lazarillo_mongodb_backend
    ports:
      - "80:80"
    volumes:
      - appdata:/var/www
    depends_on:
      - lazarillo_mongodb_backend
    networks:
      - backend

  lazarillo_mongodb_backend:
    build:
      context: mongodb
      dockerfile: Dockerfile
    image: lazarillo_mongodb_backend
    container_name: lazarillo_mongodb_backend
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: lazarillo
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  appdata:
    driver: local
  mongodbdata:
    driver: local
