version: '3'
services:

  lazarillo_admin_backend:
    build:
      context: app
      dockerfile: Dockerfile
    image: digitalocean.com/flask-python:3.10
    container_name: lazarillo_admin_backend
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: lazarillo_admin_db
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongo_password
      MONGODB_HOSTNAME: localhost
    volumes:
      - appdata:/var/www
    depends_on:
      - lazarillo_admin_db
    networks:
      - backend
      - frontend

  lazarillo_admin_db:
    image: mongo
    container_name: lazarillo_admin_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: lazarillo_admin_db
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: digitalocean.com/webserver:latest
    container_name: lazarillo_admin_webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "false"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - lazarillo_admin_backend
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  appdata:
    driver: local
  mongodbdata:
    driver: local
  nginxdata:
    driver: local
